name: Deploy to Dokploy

on:
  push:
    branches: ["main"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X 'POST' \
          'https://${{ secrets.DOKPLOY_DOMAIN }}/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ secrets.DOKPLOY_APP_ID }}"
              }
          }'